# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 643b7f9b8442adcfe11c11f5d22e3ad54388f45216775f11a71344f12125636fe81a30fa38aee7e97be14f5da2bdd341debb0df7bccad676e2812abf83d497e7

test:
  secret_key_base: b33e2cab3cf60aafb200a8355b1cb17753f1261eebe4a3918a7a9801c5a2c08227539d0550ef000f62c854852d15728fc72af70e2a54fa7bb17aa514b2020c21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
